### ISSUE TITLE
Minor point - New and Make

### ISSUE THREAD

**Issue by xogeny** [blang/semver#15]
Thanks for reworking this to be value oriented.  I revisited my project where I was using this and forgot I had reported the whole pointer thing and wondered "Why did I use pointers everywhere".  Then I came here and checked the issues to see that I had raised the issue with you and was pleased to see that `v2` was now available.  That was perfect since I was rewriting my code to use values anyway.

However, one minor thing I noticed. You still have a function called `New`.  The Golang convention here is to use `Make` for functions that return values and `New` for ones that return pointers.  So I'd suggest you change `New` to `Make`.  You could include `New` as well...but it should return a pointer.  But I'm not how useful that would be for someone since the whole API is now value based.  But the value versions of the methods should work with the pointers (just not the other way around).  So it shouldn't hurt to have both `New` and `Make`.  I could submit a PR if you want.

Thanks again!

**Comment by blang** [comment]
Thx for pointing that out, fixed in [v3](https://github.com/blang/semver/tree/v3.0.0)
