### ISSUE TITLE
Semver Range Support?

### ISSUE THREAD

**Issue by lightglitch** [blang/semver#17]

**Comment by cbandy** [comment]
What's a "semver range?"

**Comment by lightglitch** [comment]
A version range is a set of comparators which specify versions that satisfy the range.

https://github.com/npm/node-semver#ranges
https://gist.github.com/FichteFoll/a93e064468a6d9b14ea2

**Comment by blang** [comment]
Already thought about that a while ago. There may be some interesting use cases and we could also build a command line utility like node-semver does. Sadly, i don't have time for this right now, maybe in 1-2 month

**Comment by mishak87** [comment]
@blang I will play with it little bit over weekend and send pull if it will result in something useful.
I would appreciate if you could send me some pointers or links to similar implementations.

**Comment by blang** [comment]
I would take a look at the node.js implementation (linked above) but i would not make a `cli` out of it.

The scenario: Your app get "2.0.1" as a string and you need to check if its `>=2.0.0` and `<3.0.0`.
Node's implementation has a bnf grammar which describes the possible comparators: https://github.com/npm/node-semver/blob/master/range.bnf

They use regex all over but i would love to stick to a manual parser which might be not that trivial.

**Comment by blang** [comment]
Implemented in https://github.com/blang/semver/commit/aea32c919a18e5ef4537bbd283ff29594b1b0165

**Comment by mishak87** [comment]
Thank you!
