### ISSUE TITLE
Coverage is lower than what readme says

### ISSUE THREAD

**Issue by ferhatelmas** [blang/semver#22]
> Fully tested (Coverage >99%)

But it seems coverage is around 87% according to batch in readme. 

Please, don't get me wrong, it's just to increase awareness and we can make it great again. If you wish, I can even give a hand.

**Comment by blang** [comment]
You're absolutely right,
have a look at [Coveralls statistics about the last builds](https://coveralls.io/github/blang/semver).
Last commit 99c25b2dbb9b8a6389fab5fb785ee7428a7a6ab8 #31 decreased the coverage but only included json files. Any idea how to fix that problem in coveralls?

**Comment by blang** [comment]
Goveralls included the subdirectory `examples` by default. Adding the `-package` flag to goveralls fixed the issue, coverage back to normal.

**Comment by ferhatelmas** [comment]
Back to awesomeness :+1:
