### ISSUE TITLE
Convert semver.Range to string?

### ISSUE THREAD

**Issue by scottillogical** [blang/semver#31]
Thanks for this project, I'm sorry if I missed this in the godocs, but is there a way to get a string representation of a range?  For example I have a range that is equal to >=1.0.0 AND <= 3.0.0, would like to get that as a string to show to users.   Thanks!

**Comment by blang** [comment]
Sorry there is currently no way to do that. A rework of the range system is almost done, which supports this and other features.
Sadly it will take a couple of weeks until i get back to work at it

**Comment by scottschulthess** [comment]
Cool thanks, I just stored the string on my end, easy enough to workaround
