### ISSUE TITLE
semver doesn't support major or major.minor versions

### ISSUE THREAD

**Issue by kayrus** [blang/semver#40]
[This string](https://github.com/blang/semver/blob/c5e971dbed7850a93c23aa6ff69db5771d8e23b3/semver.go#L233) explicitly checks for major.minor.patch version. In certain cases there could be `0.1`, `1.0` or even `2` version formats.

**Comment by blang** [comment]
In the semver specification, major.minor.patch needs to be present
https://semver.org/#spec-item-2
