### ISSUE TITLE
Wrong module name

### ISSUE THREAD

**Issue by sirkon** [blang/semver#53]
Hi! Thank you for a great package!

There is a caveat though: the package at its v3 major revision but it doesn't have `/v3` suffix in its module name.

IMO you should either to drop all versions history or give it a proper name, i.e. `github.com/blang/semver/v3`

**Comment by hanzei** [comment]
The problem is, that this is a breaking change. Hence, this must be part of `v4`. See also https://github.com/blang/semver/pull/48#issuecomment-483043634.

**Comment by sirkon** [comment]
got it, thank you for fast response
