### ISSUE TITLE
ParseTolerant now fails on a valid semver

### ISSUE THREAD

**Issue by smarterclayton** [blang/semver#55]
After #47  I noticed that the following (which semver.ParseTolerant had previously accepted) now no longer parses:

semver.Parse("4.1.0-0.nightly") is returned as 4.1.0-0.nightly

but after this change

semver.ParseTolerant("4.1.0-0.nightly") errors with strconv.ParseUint: parsing "": invalid syntax

I think the fix is that the "remove leading zeroes" part of that change needs a more accurate check than `len(p) >1` - probably needs to be looking to the first dot, not the whole string.

**Comment by lymisscarol** [comment]
Hi, is there any plan to fix this issue or merge the above pull request?

**Comment by Zalgo2462** [comment]
Hello, I am also affected by this bug. I have fixed it by pinning my dependency to version 3.5.1. However, I would very much appreciate a fix for this.
