### ISSUE TITLE
proposal: remove pre-release versions >1.0.0 increment constraint

### ISSUE THREAD

**Issue by lfaoro** [blang/semver#59]
What is the motivation behind stopping pre-releases from being incremented? I read the SemVer spec and couldn't find this rule, could you point out where you've seen this constraint?

```go
// IncrementMinor increments the minor version
func (v *Version) IncrementMinor() error {
        //-----
	if v.Major == 0 { // why?
		return fmt.Errorf("Minor version can not be incremented for %q", v.String())
	}
        //-----
	v.Minor += 1
	v.Patch = 0
	return nil
}
```

Would you mind me submitting a PR to remove it?

**Comment by x899** [comment]
If the version is 0.*.*, the project is still in the development phase and not yet publicly released.
A publicly-released project starts at 1.0.0.

**Comment by lfaoro** [comment]
@x899 true, although I still want to manipulate the tags of unreleased projects, why stop the user from doing so?

**Comment by x899** [comment]
**Use Case:** I want to check the package that I am using is up-to-date, so I get the version number from the package website or something and compare it with the local package using **semver**.

I can't seem to find the use case where the unpublished package needs semver?

**Comment by lfaoro** [comment]
Packages are published before reaching v1 all the time. You can't find a use case because you're not looking. 

`cloud.google.com/go v0.43.0` -- good use case?
`github.com/stretchr/objx v0.1.1` - https://github.com/stretchr/objx/releases
`github.com/google/go-cmp v0.3.1` - https://github.com/google/go-cmp/releases
https://github.com/fatih/set/releases 
https://github.com/src-d/go-mysql-server/releases 
etc..

As you can see, plenty of use cases, I can't use the semver library to manipulate the tags of any of those packages.

Please reconsider, I've submitted a PR #60

**Comment by blang** [comment]
Thanks for the contribution, the PR_60 was merged. Im working on the versioning issue
