### ISSUE TITLE
Cannot install using go modules

### ISSUE THREAD

**Issue by lootek** [blang/semver#63]
v3.5.1 is the last tagged version that doesn’t include a go.mod file
The newer has a go.mod file but is invalid since the module needs to have a /v3 suffix then

see https://github.com/golang/go/issues/31944#issuecomment-528272174 for more

**Comment by carldunham** [comment]
because he loves irony

**Comment by EugenMayer** [comment]
Any reason why this is not picked up - fairly important issue ( at least for me )

**Comment by malkhamis** [comment]
I am also wondering why this is not picked up!

**Comment by EugenMayer** [comment]
This project seems to be fairly dead, maybe we should consider supporting one of it;s successors https://github.com/jmorrell/semver or alike

**Comment by blang** [comment]
We will introduce a proper versioned variant soo, please stay tuned

**Comment by hangyan** [comment]
This is very irresponsibility

**Comment by blang** [comment]
This issue should be solved with the release of [V4](https://github.com/blang/semver/releases/tag/v4.0.0) 

Thanks for your patience
