### ISSUE TITLE
How to compare the pre-release version?

### ISSUE THREAD

**Issue by jianzhangbjz** [blang/semver#64]
Why the [result](https://play.golang.org/p/7CvrBT-zM7s) is `false`? I think 201912060615 < 201912111117. How can I make it return `true`.?
```golang
package main

import (
	"fmt"
	"github.com/blang/semver"
)

func main() {
	inRange, err := semver.ParseRange(">=4.3.0 <4.3.0-201912111117")
	if err != nil {
		panic(err)
	}

	version := semver.MustParse("4.3.0-201912060615")

	// Check if the version meets the constraints. The a variable will be true.
	fmt.Printf("within range: %t", inRange(version))
}
```

**Comment by makkes** [comment]
@jianzhangbjz:

Your range start `>=4.3.0` demands the version to be at least `4.3.0`. However, `4.3.0-201912060615` is a **pre-release** version so it is actually lower than `4.3.0`.

https://semver.org/#spec-item-11:
> When major, minor, and patch are equal, a pre-release version has lower precedence than a normal version:
>
> Example: 1.0.0-alpha < 1.0.0.

**Comment by jianzhangbjz** [comment]
@makkes Ah, I see now, many thanks!
