### ISSUE TITLE
1.0.0-rc1 is greater then 1.0.0-rc11

### ISSUE THREAD

**Issue by EugenMayer** [blang/semver#65]
I does work for 

- 1.0.0-rc1 < 1.0.0-rc2
- 1.0.0-rc10 < 1.0.0-rc11

but is broken for

- 1.0.0-rc1 > 1.0.0-rc11
- 1.0.0-rc1 > 1.0.0-rc12

And so on ( comparing a 2 digit rc vs a 1 digit rc )

**Comment by blang** [comment]
Works as expected according to spec: https://semver.org/#spec-item-11

> identifiers consisting of only digits are compared numerically and identifiers with letters or hyphens are compared lexically in ASCII sort order

To use proper release candidates, use:

> Example: 1.0.0-alpha < 1.0.0-alpha.1 < 1.0.0-alpha.beta < 1.0.0-beta < 1.0.0-beta.2 < 1.0.0-beta.11 < 1.0.0-rc.1 < 1.0.0.

Thanks

**Comment by EugenMayer** [comment]
i see, thank you
