### ISSUE TITLE
Confusing behavior of Range with version with release tag

### ISSUE THREAD

**Issue by dinhxuanvu** [blang/semver#67]
If I have a range `>=4.3.0` and I pass a version with release tag such as `4.3.0-20191231`, the result will be False. However, if I use range `>4.3.0-0`, then the result will be True. This is a bit of confusing behavior because from my perspective `4.3.0-20191231` should be a part of the range `>=4.3.0`. I wonder if someone can explains this behavior a bit for me.

Here is the code if someone wants to test it out on Playground:
```
package main

import (
	"fmt"
	"github.com/blang/semver"
)

func main() {
	ra, _ := semver.ParseRange(">=4.3.0")

	if ra(semver.MustParse("4.3.0-201912000000")) {
		fmt.Print("True")
	} else {
		fmt.Print("False")
	}
}
```

Thanks so much in advance.

**Comment by blang** [comment]
A pre-release version has always a lower precedence than a normal version:
https://semver.org/#spec-item-11

> When major, minor, and patch are equal, a pre-release version has lower precedence than a normal version.
